version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_password
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintech-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fintech-app
    environment:
      - DATABASE_URL=postgresql://fintech_user:fintech_password@postgres:5432/fintech_db
      - JWT_SECRET=your-super-secret-jwt-key-for-docker-development
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - fintech-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:

networks:
  fintech-network:
    driver: bridge
